### PR TITLE
Add a section for CSV

### PR DESCRIPTION
**Pull request by jbax**
Adding [uniVocity-parsers](https://github.com/uniVocity/univocity-parsers) to the list.

### CODE REVIEW

**Comment by akullpp** [comment]
Disclosure? You are the author of the said framework with about 60 stars.

**Comment by jbax** [comment]
Yes, I'm the author. This is a new library but it's quickly picking up steam because it is very superior than what other libraries offer, both in terms of speed and out-of-the box functionalities. Apache camel already introduced integration this parser. See in http://camel.apache.org/univocity-parsers-formats.html

**Comment by akullpp** [comment]
Thanks for clarification. But if it is superior, why create a whole new section since adding other CSV libraries won't be necessary?

Would it be acceptable to add the library to the Datastructures section and change the purpose of the section to read/write specific datastructures like CSV?

**Comment by jbax** [comment]
CSV is not exactly a data structure, but a text format such as JSON, which also has a specific section. I created the CSV section to be consistent.

**Pull request merged**
