### PR TITLE
refactor rest, web and micro-service categories.

### PR DESCRIPTION
**Pull request by Moshe-Immerman**

### CODE REVIEW

**Comment by akullpp** [comment]
The moved libraries do not enforce any kind of architecture, why move them to Microservices?

**Comment by Moshe-Immerman** [comment]
@jbduncan  So my reasoning on breaking them down:

* A web framework is about building user interfaces delivered through web browsers
* A microservice is really about creating a modern HTTP application with as little boilerplate, and as few dependencies as possible [1]
* A REST Server framework is used for building microservice containers, not really for end user use.

A microservice framework may or may not make building REST style services easier - However, it isn't it's defining factor. e.g. Dropwizard, Restlet, rest.li are about microservices, REST just happens to be the style they chose to make a first class citizen

If you cannot combine a web application framework with at least one microservice framework, then it is a microservice framework with a built-in web application framework - maybe these should be put in a new Full Stack Web Framework category?

[1] https://martinfowler.com/articles/microservices.html

**Comment by jbduncan** [comment]
Hmm...

I admit that I do not know enough about microservices to feel confident discussing them in detail. But IMO calling microservices as just "modern HTTP application(s) with as little boilerplate, and as few dependencies as possible" is very misleading. This is because, by my understanding, there are supposed to be _many_ microservices within a microservices system, where each microservice fills a very specific role, and frameworks like Dropwizard and Spring Boot don't help to enforce that (as they can just as easily be used to build monolithic applications, and they are also designed specifically to be a web service framework and a server-based web application framework respectively).

But I'd be glad to be proven wrong on this! (For example, if you could point me to the relevant parts of Dropwizard's and Spring Boot's respective websites, or point me to the relevant part of that article from Martin Fowler you linked earlier.)

@akullpp Do you have any other thoughts on this?

**Comment by Moshe-Immerman** [comment]
@akullpp @jbduncan 

I don't see how any library could enforce an architectural style - there is no clear cut definition for a microservice, how many microservices are deployed and how large each service is will always differ. 

A micro service framework needs to expose a service (99% of the time over HTTP) - Deploying and exposing that service should be as easy as possible to allow for creating many microservices.

Spring MVC is a web application framework it can be combined with Spring Boot or Dropwizard (Using http://www.dropwizard.io/1.1.0/dropwizard-jetty/apidocs/io/dropwizard/jetty/setup/ServletEnvironment.html)

The same applies to Spring boot - you can run any of the web applications on Spring boot by registering their servlets - (not all micro service frameworks support servlets, or at least not publicly)

Some of the frameworks include more batteries than others, either built-in, or through built-in modules or a via plugin ecosystem

A service registry/disovery library can be used within a microservice environment, but there is nothing preventing using it for monoliths, or having a microservice environment with a dynamic registry - so I moved them to the distributed applications section.

I also removed barantine as it is GPL licenses and only 50 stars

**Comment by Moshe-Immerman** [comment]
(I will resolve merge conflicts, once you are happy in principal)

To clarify, when I say "modern HTTP application(s) with as little boilerplate, and as few dependencies as possible" - I mean any library that meets those less subjective criteria, allows you to build a microservice architecture with independent and isolated components and is, therefore, a microservice framework.

You can abuse a micro service framework to make a monolith and your development velocity will remain pretty much the same (compared to a monolith platform).  but if you abuse a monolith platform to create microservices, your development velocity will go down.  


I found a few more sources:

[gokit](https://gokit.io/) compares itself to Dropwizard and Spring Boot as microservice libraries  
[https://spring.io/blog/2015/07/14/microservices-with-spring](https://spring.io/blog/2015/07/14/microservices-with-spring)  
[https://dzone.com/articles/spring-boot-creating](https://dzone.com/articles/spring-boot-creating)

**Comment by jbduncan** [comment]
I'm on the edge about this change. On one hand, I'm more convinced now that calling Spring Boot, Dropwizard _et al._ as microservice frameworks is okay. On the other hand, this PR has now affected so much of list that I'm struggling to mentally parse everything.

So unless @akullpp has any objections, then @Moshe-Immerman I'd like it if you could split this PR into smaller, logical PRs so that it's easier to review everything.

**Comment by Moshe-Immerman** [comment]
@jbduncan sounds good, queued up a few

**Comment by jbduncan** [comment]
Thanks @Moshe-Immerman!

I'll be busy over the next 7 days or so with my university dissertation, so I may not have time to review your new PRs until it's finished. :)

**Pull request closed without merging**
