### PR TITLE
 Add failsafe actuator

### PR DESCRIPTION
**Pull request by MALPI**
Add failsafe-actuator library. Not sure though if this should be part of Monitoring or Distributed applications.

### CODE REVIEW

**Comment by jbduncan** [comment]
I'd struggle to call this project awesome at a glance because, despite having a Git history that goes back at least 11 months, it only has 3 watchers and 5 stars, is under seeming incubation, and IMO seems _too_ niche to be considered valid by the contribution guidelines' (admittedly vague) definition of "niche"

@MALPI Can you elaborate what is it about this project that makes you think or feel that it's awesome?

**Comment by MALPI** [comment]
@jbduncan I'll try to. ;-)

First thing what makes it awesome is that it enables one to use failsafe "spring native". Which means you can use dependency injection in order to inject circuit breakers. Furthermore circuit breakers which have been injected with the lib will provide monitoring data on spring actuator endpoint. 

In other words it makes the failesafe library more easily usable for spring users.

**Comment by jbduncan** [comment]
@MALPI Thanks for taking the time to explain. :)

I think this is a good argument for adding failsafe-actuator to an awesome-spring list! (I've managed to find https://github.com/JStumpp/awesome-spring, but it's empty and has not seen commits for 2 years?)

I'm still hesitant to have failsafe-actuator added to awesome-java because we're trying now to only add stuff to awesome-java that's useful for Java developers in general, and I'd rather not add something something that's both niche and only fits in the Spring ecosystem when we already have a general entry under **Platforms** for Spring itself.

@akullpp?

**Comment by MALPI** [comment]
Good evening. Adding it to your mentioned awesome-spring list is kinda questionable since the project seems to be unmaintained.

Maybe it's beneficial to start sub-sections of the platform section. Like one for spring and one for dropwizard? Where very specific projects can still have their space but still have a limited scope within this list.

At least this "awesome-list" is widely known and so more people can benefit by these inputs?

**Comment by jbduncan** [comment]
I agree that that particular awesome-spring list is questionable to add to because of its lack of maintenance. I suggested it simply to raise that adding failsafe-actuator to an awesome-spring list (not necessarily that one) might be a better idea than adding it to awesome-java.

> Maybe it's beneficial to start sub-sections of the platform section. Like one for spring and one for dropwizard? Where very specific projects can still have their space but still have a limited scope within this list.

Okay, I wasn't sure about this at first, but now you've half-convinced me. Can you give a concrete example?

**Comment by akullpp** [comment]
A "Spring" category was discussed but the consequences would be too complex. If you don't find any suitable list, we can add it and see how it goes.

**Comment by jbduncan** [comment]
@MALPI I just wanted to follow up on this. Are you at a stage yet where you can share with us a PR with a concrete example of what you had in mind?

**Comment by MALPI** [comment]
Hey, sorry I am on vacation right now but definitely want to spent time on this. I will be back in 2 weeks.

**Comment by MALPI** [comment]
@jbduncan @akullpp This is how I thought it could be? What do you think? OfC there is plenty of space for other extensions.

**Comment by akullpp** [comment]
I don't like the idea of separating this in categories since I don't see the practicality.

**Comment by jbduncan** [comment]
I mostly agree with @akullpp. On one hand I half want this to work; on the other hand, in its current state it renders as something which doesn't look nice to look through IMO...

**Comment by MALPI** [comment]
I'd appreciate some proposal how it would look better for you, @jbduncan @akullpp

**Comment by jbduncan** [comment]
I wonder if it would render more nicely like this:

----

# Markdown
```markdown
* [CUBA Platform](https://cuba-platform.com) - High level framework for development of enterprise applications with rich web interface, based on Spring, EclipseLink and Vaadin.
* [Dropwizard](https://dropwizard.github.io/dropwizard/) - Opinionated framework for setting up modern web applications with Jetty, Jackson, Jersey and Metrics:
    * [Dropwizard Cassandra](https://github.com/composable-systems/dropwizard-cassandra) - Provides useful functionality for Dropwizard apps that communicate with Cassandra clusters.
* [Light-Java](https://github.com/networknt/light-java) - A fast, lightweight and productive microservices framework with [security](https://github.com/networknt/light-oauth2) built in.
* [Orienteer](https://github.com/OrienteerBAP/Orienteer) - Open source business application platform for rapid configuration/development of CRM, ERP, LMS and other applications.
* [Spring](http://projects.spring.io/spring-framework/) - Provides many packages ranging from dependency injection to aspect-oriented programming to security:
    * [Failsafe Actuator](https://github.com/zalando-incubator/failsafe-actuator) - Out-of-the-box monitoring for Failsafe in a Spring Boot environment.
```

----

# Rendered
* [CUBA Platform](https://cuba-platform.com) - High level framework for development of enterprise applications with rich web interface, based on Spring, EclipseLink and Vaadin.
* [Dropwizard](https://dropwizard.github.io/dropwizard/) - Opinionated framework for setting up modern web applications with Jetty, Jackson, Jersey and Metrics:
    * [Dropwizard Cassandra](https://github.com/composable-systems/dropwizard-cassandra) - Provides useful functionality for Dropwizard apps that communicate with Cassandra clusters.
* [Light-Java](https://github.com/networknt/light-java) - A fast, lightweight and productive microservices framework with [security](https://github.com/networknt/light-oauth2) built in.
* [Orienteer](https://github.com/OrienteerBAP/Orienteer) - Open source business application platform for rapid configuration/development of CRM, ERP, LMS and other applications.
* [Spring](http://projects.spring.io/spring-framework/) - Provides many packages ranging from dependency injection to aspect-oriented programming to security:
    * [Failsafe Actuator](https://github.com/zalando-incubator/failsafe-actuator) - Out-of-the-box monitoring for Failsafe in a Spring Boot environment.

----

Note that I've purposely removed _Spring Boot_ from the **Spring** sublist, because I think it better belongs in **Web Frameworks**.

Also note that I've changed the description of _Failsafe Actuator_ so that it reads a little better.

**Comment by jbduncan** [comment]
Hmm, I'm now questioning again the usefulness of categorising things like this, because I'm sure people will argue on where items like _Spring Boot_ would best live: I personally believe that it best lives in **Web Frameworks**, whereas others will argue that it best lives in **Spring**.

**Comment by jbduncan** [comment]
I've also realised that I'm still against the idea of adding Failsafe Actuator (or Dropwizard Cassandra for that matter) to awesome-java, as I still believe they're too niche for the list and deserve their own awesome-{spring,dropwizard} lists, even if it means those lists have to be started up by someone else.

**Comment by MALPI** [comment]
Fair enough points. Although I doubt that Spring-Boot actually is a web framework but I don't want to fight that. ;-). I'll just give it a try to compile an awesome Spring List ;)

**Comment by jbduncan** [comment]
Sounds good to me. ;)

(I think people categorise Spring Boot differently based on their experience/understanding of it: some use it for web apps, others for desktop apps, others for monolithic web services, and others yet for microservices. It's not easy to come up with a category that everyone's happy with. ;) )

**Comment by akullpp** [comment]
Added with #4ed1ed989cfd330b03f3601470519fafe447c365

**Pull request closed without merging**
