### PR TITLE
Added Facebook Infer

### PR DESCRIPTION
**Pull request by codehate**
Added (Facebook Infer](http://fbinfer.com/)

### CODE REVIEW

**Comment by jbduncan** [comment]
Currently Facebook Infer only targets Android (as far as Java's concerned), so I'd personally hesitate to have it listed in awesome-java.

My reason for being hesitant is because awesome-java used to list [Picasso](http://square.github.io/picasso/) as an awesome library, but eventually it was removed because it could only be used on Android, and awesome-java is supposed to be a place for libraries that can be used on most or all flavours of Java.

**Comment by codehate** [comment]
@jbduncan I doubt your thought that Infer only targets Android, If you have a look at Infer homepage, the [preview gif shown clearly targets Java](https://asciinema.org/api/asciicasts/32101?speed=2&autoplay=true&loop=true&t=23), and [Infer's about page](http://fbinfer.com/docs/about-Infer.html) states:

> Infer is a static program analyzer for **Java**, C, and Objective-C, written in OCaml.

**Comment by jbduncan** [comment]
Oh, my apologies @codehate, it seems I spoke too soon! Thanks for correcting my misunderstanding on Infer's applicability to Java code in general. :+1:

In that case, I think it's worth considering including this in awesome-java.

@akullpp, thoughts?

**Comment by akullpp** [comment]
The page clearly states that the use case is for mobile apps.

**Comment by jbduncan** [comment]
Well, yes, they do state that on the main page, but I think it's a misleading description.

I dug into the [about page](http://fbinfer.com/docs/about-Infer.html) just now, and it explains that although Infer is only used at Facebook for their Android and iOS apps, it can also be used to analyse C code and bog-standard Java programs that can be compiled with `javac`. See [this preview gif on the homepage](https://asciinema.org/api/asciicasts/32101?speed=2&autoplay=true&loop=true&t=23) for an example of how Infer can analyse normal Java code.

So the way I see it, Infer actually works a bit like Google's error-prone tool or FindBugs, the main difference being it uses a couple of novel (i.e. very recent) software verification techniques called **separation logic** and **bi-abduction** to do the static analysis.

**Comment by codehate** [comment]
@jbduncan Great! Thanks for the explanation. So, are you certain to add Infer to awesome-java?

**Comment by jbduncan** [comment]
Hi @codehate, I actually don't have write access to awesome-java, so you'll have to wait patiently for @akullpp to have his say on whether Infer is sufficiently Java-orientated and awesome enough to be added to the list. :)

**Comment by codehate** [comment]
@jbduncan Sure, let's wait for @akullpp call

**Pull request merged**
