### PR TITLE
added Governator

### PR DESCRIPTION
**Pull request by liviutudor**

### CODE REVIEW

**Comment by jbduncan** [comment]
Nebula and the Gradle Docker plugin are more appropriate for [awesome-gradle](https://github.com/ksoichiro/awesome-gradle) I think. :)

**Comment by liviutudor** [comment]
Oh I was so not aware of that! Thank you I will add them there and remove them from here.
Is Governator though still a valid entry? Shall I push an update with just that?
Thanks for taking the time to review this btw!

**Comment by liviutudor** [comment]
I've updated this just in case you still think it's worthy

**Comment by jbduncan** [comment]
I think the description for Governator is too long. How about something like this?
> Extensions and utilities that enhance Google Guice.

What do you think @akullpp?

**Comment by liviutudor** [comment]
agreed, made the change.

**Pull request merged**
