### PR TITLE
JObfuscator

### PR DESCRIPTION
**Pull request by PELock**
Hi, can you include my little project - JObfuscator, a Java source code obfuscator? Thank you :)

### CODE REVIEW

**Comment by shathor** [comment]
In the link I don't find any Java source code and free-tier.

**Comment by PELock** [comment]
It's the main product description page, the product is available online as (demo version is fully usable, while the product is commercial)

https://www.pelock.com/products/jobfuscator

as a library for PHP and Python

https://www.pelock.com/products/jobfuscator/api

has standalone clients for Windows & Linux

https://www.pelock.com/products/jobfuscator/download

**Comment by shathor** [comment]
From contribution guideline:

> (iii) If commercial, it has clear pricing and at least one free tier.

Also:

> (a) widely recommended, regardless of personal opinion
> (b) highly discussed in the community due to its innovative nature
> (c) absolutely unique in its approach and function
> (d) a niche product that fills a gap

As for d) there are several more widely-used open source options. E.g. [ProGuard](https://github.com/Guardsquare/proguard) or [yGuard](https://github.com/yWorks/yGuard),

**Comment by PELock** [comment]
(iii) Pricing https://www.pelock.com/products/jobfuscator/buy demo mode is free to use and try basic obfuscations

(a) it has just been released a month ago
(b) as above
(c) it's the only SOURCE CODE OBFUSCATOR for Java all others are BYTECODE obfuscators
(d) only java source code obfuscator on the market right now

**Pull request merged**
