### PR TITLE
Added Functional Java

### PR DESCRIPTION
**Pull request by danieldietrich**
Created a new section 'Functional Programming' containing one popular entry.

### CODE REVIEW

**Comment by akullpp** [comment]
Wouldn't it be better suited to add it to the Misc section since it's only one entry? Or you could add other functional libraries.

**Comment by danieldietrich** [comment]
Yes. I think it's worth to open a section dedicated to FP as of the introduction of lambdas with Java 8.

There are two functional libraries which gained popularity within the last year:

* [jOOL](https://github.com/jOOQ/jOOL)
* [Javaslang](https://github.com/javaslang/javaslang) / [website](http://javaslang.com)

The latter is my own project, so an upvote of someone else would be great in order to not let it look like self-promotion.

**Comment by akullpp** [comment]
Please add them as well.

**Comment by danieldietrich** [comment]
Thank you, Sir! :-)

**Comment by ggalmazor** [comment]
+1

**Comment by luisartola** [comment]
+1

**Comment by krisskross** [comment]
+1

**Pull request merged**
