### PR TITLE
Add RR4J

### PR DESCRIPTION
**Pull request by Kartikvk1996**
Added RR4J under the Miscellaneous section. @akullpp

### CODE REVIEW

**Comment by Kartikvk1996** [comment]
@akullpp  Can we commit this?

**Comment by StevenCurran** [comment]
Personal untested projects should not be part of this list imo.

**Comment by sproket** [comment]
It's a pretty cool project!

**Comment by shathor** [comment]
Looks pretty awesome and innovative. I don't know of anything similar, open source to exist (there is LiveRecorder https://undo.io/solutions/products/java/).
But I've not tried it out and I'm not sure how stable it is. It could have some more unit tests too.

**Pull request merged**
