### PR TITLE
Update iText commercial icon

### PR DESCRIPTION
**Pull request by Moshe-Immerman**

### CODE REVIEW

**Comment by jbduncan** [comment]
LGTM.

@akullpp, do you agree that it looks good? If so, would you like me to merge this in? For awesome-java, does one usually merge PRs by "create a merge commit", "squash and merge", or "rebase and merge"?

**Comment by akullpp** [comment]
It's fine either way. I normally just press the button. ;)

**Comment by jbduncan** [comment]
;)

**Comment by jbduncan** [comment]
> If somebody got the time I would recommend squashing and no merge commits though and using semantic commit messages.

Okay... so am I right to understand from this sentence that both "merge commit" and "rebase and squash" are acceptable PR-merge strategies for me to use for future PRs to awesome-java?

**Comment by akullpp** [comment]
Yup.

**Pull request merged**
