### PR TITLE
Added hprose

### PR DESCRIPTION
**Pull request by andot**

### CODE REVIEW

**Comment by pacher** [comment]
I want to point out that the docs(wiki) are only in Chinese\Japanese\Korean, no javadocs, so it does not seem to be useful for the rest of the world. May be some local\localized awesome list is the better place for it?

P.S. www.hprose.com and www.hprose.org don't have english version

**Comment by andot** [comment]
It's an RPC library, the javadocs can't describe how to use it, so we're going to provide a separate document and tutorial to introduce how to use it, but now, it only has Chinese documents, there's no one to help us to translate it to English, but later maybe.

**Comment by akullpp** [comment]
Please refer to https://github.com/akullpp/awesome-java/issues/384#issuecomment-233122944

If you provide a translation in English, I'd be very happy to add it.

**Comment by andot** [comment]
@akullpp, Thank you, I will add English document and tutorial later.

**Pull request closed without merging**
