### PR TITLE
Add Sentry Java SDK

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
.. and new section for "Error Reporting".

### CODE REVIEW

**Comment by shathor** [comment]
There is already a section "Code Analysis" where you also find similar projects SonarQube, Sourcetrail, etc.. I suggest moving Sentry there and potentially reword the description of the section to include "error reporting".

**Comment by maciejwalkowiak** [comment]
- yes, you can host it with full functionality for free
- it's not a code analysis tool - it analyses exceptions and error logs reported in runtime

**Comment by shathor** [comment]
How about the "Monitoring" section then? I'd refrain from adding new, ever more specific sections.

**Comment by maciejwalkowiak** [comment]
Yes, monitoring sounds good, especially with Sentry's performance monitoring capabilities. I'll update PR.

**Comment by maciejwalkowiak** [comment]
Thanks! Got distracted by other things..

**Pull request merged**
