### PR TITLE
Add Spock

### PR DESCRIPTION
**Pull request by Charlew**

### CODE REVIEW

**Comment by dariodariodario** [comment]
does spock have a java API?

**Comment by jmsalcido** [comment]
it's groovy, IMO it should be part of this repository with a disclaimer, since tests are written in groovy for the JVM.

**Comment by st-h** [comment]
It's a broadly accepted way to test your java code. And it's awesome imho (just in case anyone cares 😂)
However, it seems to have it's history with this repository already https://github.com/akullpp/awesome-java/search?q=spock&type=Commits

**Comment by jmsalcido** [comment]
@st-h I care :) thanks for the info about already discussed. Probly we should not add this... again.

**Pull request closed without merging**
