### PR TITLE
Add DolphinScheduler

### PR DESCRIPTION
**Pull request by hugogu**
Apache DolphinScheduler is the modern data orchestration platform. Agile to create high performance workflow with low-code. It is also provided powerful user interface, dedicated to solving complex task dependencies in the data pipeline and providing various types of jobs available out of the box.

### CODE REVIEW

**Comment by vega0707** [comment]
你好，邮件已收到，谢谢

**Comment by akullpp** [comment]
How's it related to the Java programming language, the got an API?

**Comment by shathor** [comment]
> How's it related to the Java programming language, the got an API?

Looks like it's written in Java. So I guess you can also define a workflow in code naturally. But I don't see any examples. Interestingly they also made a Python SDK just for that.

**Comment by vega0707** [comment]
你好，邮件已收到，谢谢

**Pull request closed without merging**
