### PR TITLE
web framework: jooby

### PR DESCRIPTION
**Pull request by jknack**
Scalable, fast and modular micro web framework: http://jooby.org

### CODE REVIEW

**Comment by akullpp** [comment]
What is the unique selling point of the framework?

**Comment by jknack** [comment]
I'm not selling anything, so will mention features of the framework:

* It is a micro framework (small, fast and scalable)
* Simplifies Java Web Development. Easy to learn.
* Multi-server including Netty, Undertow and Jetty (you pick your favorite)
* Web-Sockets
* Offers two programming models:
  1. Script (like expressjs or sinatra)
  2. MVC (like Jersey, Spring)
* You can write the your app in JavaScript.
* Extensive list of modules, where most notables are:
  1. Swagger for documenting your API
  2. Assets module similar to grunt/gulp that run on top of v8 using jni bindings
  3. HTTP Session on top of redis, memcached, etc...

**Comment by akullpp** [comment]
Thanks for explaining. Selling point means unique features. 

Could you please adapt the description, it reads like just another buzzword MVC framework.

**Comment by akullpp** [comment]
Added manually in features/pending-prs

**Pull request closed without merging**
