### PR TITLE
Open JDK distribution list

### PR DESCRIPTION
**Pull request by osigida**
a list of Open JDK Distributions by different vendors.

### CODE REVIEW

**Comment by akullpp** [comment]
Please don't create a single subsection, this PR would be fine if you add the entries to the JDK section, don't you think?

**Comment by jbduncan** [comment]
[Azul's Zulu OpenJDK](https://www.azul.com/downloads/zulu/) should also be mentioned in this PR, but other than that and and @akullpp's suggestion, this LGTM. :)

**Comment by osigida** [comment]
> Please don't create a single subsection, this PR would be fine if you add the entries to the JDK section, don't you think?

@akullpp, Open SDK Distributions are not something new or different to OpenSDK by Oracle, it is just a packaging by different vendors, to avoid future licence issues with Oracle. So it supposed to be the same as Open SDK.
That is why I added it as a sub list to SDK list.

However, I feel it is important to keep this way or another.
Please let me know if you still insist to merge it to SDK list, and I'll update the PR.

**Comment by akullpp** [comment]
I fixed the PR, there has been duplicates and missing formats.

**Pull request merged**
