### PR TITLE
Jinq added to database section

### PR DESCRIPTION
**Pull request by JensPiegsa**

### CODE REVIEW

**Comment by jbduncan** [comment]
@JensPiegsa Thanks for the PR!

Can you please apply proper casing to the sentence (so "typesafe" -> "Typesafe", and "Jooq" -> "jOOQ").

Can you also expand the description to give a bit more detail on how JINQ differs from JOOQ and other competing libraries.

**Comment by jbduncan** [comment]
Can you also normalise "Jinq" to "JINQ". I believe "JINQ" is the proper name of the project?

**Comment by jbduncan** [comment]
Oh, terribly sorry, I think "Jinq" _is_ the proper name. (It looks like it's used more often in the documentation that "JINQ".) So please disregard my last comment. :)

**Comment by JensPiegsa** [comment]
@jbduncan Thank you for the review.

**Comment by jbduncan** [comment]
Thank _you_ @JensPiegsa. :)

LGTM now, so on the assumption that @akullpp is happy with this, I'll merge this in as soon as I can.

**Pull request merged**
