### PR TITLE
Added Hackr.io

### PR DESCRIPTION
**Pull request by rohduggal**
https://hackr.io/tutorials/learn-java

### CODE REVIEW

**Comment by Simonwep** [comment]
Nice bot.

**Comment by rohduggal** [comment]
Hey, I'm doing it manually.

**Comment by rohduggal** [comment]
image

**Comment by akullpp** [comment]
A list to Java learning materials? Why not directly add the quality stuff. I think this is an indirection we don't need and could even be abused by a referral scheme ;-)

**Pull request closed without merging**
