### PR TITLE
Add Apache Drill

### PR DESCRIPTION
**Pull request by vdiravka**
Apache Drill is an open source Apache top project.
It has a big community of users and developers. 

It is one of the most powerful tools for Big Data, RDBMS and other sources exploration. Drill supports ANSI SQL constructs and can combine data from different data sources in a single SELECT statement.

Let me know if you need more info about this project to add it to Awesome Java.

### CODE REVIEW

**Comment by vdiravka** [comment]
@akullpp Can you please or somebody else review it?

**Comment by akullpp** [comment]
@vdiravka I'm struggling to see how this library is related to the Java programming language.

**Comment by vdiravka** [comment]
@akullpp Thanks for looking into it.
This tool is fully related to the data querying. It is pretty good for queering simple flat files or querying big amount of data on the cluster (the data from FileSystem/Hive/Hbase/MapR-DB/RDBMS/MongoDB/Amazon S3/Kafka etc. can be queried and cobined via JOIN and UNION operators in one SQL query).
It is complete scalable and high performance execution engine based on [Apache Calcite](https://github.com/apache/calcite) planner (which is used for query optimizations).
Drill can be used via Drill SqlLine (shell), UI or with clients via REST API, ODBC or JDBC. The last is good for Drill's use in BI analytics tools.

Drill is pretty well extensible for adding new Storage Plugins, which can allow to query the data from any new data source (examples of plugins which can be added: Apache Iceberg, Apache Cassandra, Elasticsearch, XML, ORC, REST JSON, BlockChain etc.).
So it is great SQL tool for data. And for sure the project is written in Java (96%) https://github.com/apache/drill#apache-drill
It has a big community, which makes the project more attractive for the new contributors.

**Comment by vdiravka** [comment]
@akullpp Please let me know what is necessary to merge it or tell me why it can't be merged and then close the PR.
Thanks

**Pull request merged**
