### PR TITLE
Etcd

### PR DESCRIPTION
**Pull request by jonatan-ivanov**
Distributed reliable key-value store for the most critical data of a distributed system: https://coreos.com/etcd/

### CODE REVIEW

**Comment by jbduncan** [comment]
I think it would make more grammatical sense to say "**A reliable, distributed** key-value store..." instead of "**Distributed reliable** key-value store".

**Comment by jbduncan** [comment]
Oh, and also I just noticed that etcd is written on Go, rather than Java.

Could you explain why you think it's a good fit for awesome-java?

**Comment by akullpp** [comment]
Why "awesome Java"?

**Comment by jbduncan** [comment]
@akullpp was your question directed at me or at @jonatan-ivanov? :)

**Comment by akullpp** [comment]
I don't see an explicit relation to Java

**Pull request closed without merging**
