### PR TITLE
Adding commons-networking

### PR DESCRIPTION
**Pull request by liran2000**
Adding commons-networking

Features:

- SSE (Server-sent Events) client

Simple SSE client almost without any dependencies, did not found anything similar online, and not here in this list.

It is used in developments in a similar version.

As it is new and similar implementation not found, it is currently still cannot be widely recommended.

Note: I am the author of this SSE client.

### CODE REVIEW

**Comment by akullpp** [comment]
I'll keep this open for a while. I think it's not ideal to have the SSE client and the GNMI utils in the same project and probably should be split up to two separate modules.

**Comment by liran2000** [comment]
You are correct. Both are on separate modules already, just the repository
is common. If wanted, each can be linked to its specific module

בתאריך יום ב׳, 1 במרץ 2021, 10:07, מאת Andreas Kull ‏<
notifications@github.com>:

**Comment by liran2000** [comment]
By your suggestion, I updated the PR changes to contain only the SSE client, and the link is referring only to the specific module of SSE client.

**Comment by liran2000** [comment]
@akullpp can you merge it ? any concern ?

This is updated just for SSE Client module.

**Pull request merged**
