### PR TITLE
Clarify contribution guidelines

### PR DESCRIPTION
**Pull request by Moshe-Immerman**

### CODE REVIEW

**Comment by jbduncan** [comment]
I think it should say the following.

> Unfortunately, not every library/tool/framework can be considered. The aim of the list is to provide a concise list of noteworthy modern software. This means that suggested software meets at least one of the following criteria:
>
> (a) ...
> ...
> (d) ...
>
> It should also be developer-friendly (for example, it should have a business-friendly open source license or, if commercial in nature, have clear pricing). However, this is not strictly necessary as long as it meets one of the criteria above; we do occasionally accept GPL-licensed projects, but we will consider them more critically.

What do you think, @akullpp?

**Comment by jbduncan** [comment]
@Moshe-Immerman "Github" -> "GitHub"

**Comment by Moshe-Immerman** [comment]
my bad, I missed the emphasis on library vs application.

**Comment by jbduncan** [comment]
@Moshe-Immerman Looks much better, many thanks. :)

**Comment by jbduncan** [comment]
Waiting on @akullpp's opinion now.

**Pull request merged**
