### PR TITLE
Remove distributed databases

### PR DESCRIPTION
**Pull request by Moshe-Immerman**
awesome microservices has a similar list.

### CODE REVIEW

**Comment by jbduncan** [comment]
I disagree with this change. AFAICT, most or all of the entries under Distributed Databases are implemented in Java.

**Comment by jbduncan** [comment]
Hmm, I think I might've spoke too soon. Considering https://github.com/akullpp/awesome-java/pull/543, I'm now on in two minds about this change. :thinking:

**Comment by jbduncan** [comment]
My gut feeling now is that anything which is at least half implemented in Java deserves to stay.

**Comment by Moshe-Immerman** [comment]
I think this list is targeted at Java developers - So unless you can **use** it from Java it shouldn't be here. 

Cassandra, druid and OpenTSB don't even mention java on the homepage. 

HBase is perhaps marginal as only has official Java API, but there are plenty clients in other languages. 

Infinispan **can** be run embedded, but it kind of defeats the purpose of a distributed cache

**Comment by Moshe-Immerman** [comment]
If anything Infinispan should be moving to the caching category

**Comment by jbduncan** [comment]
@Moshe-Immerman That's a good point! I'm more convinced now that the distributed databases aren't a good fit for awesome-java.

Yeah, your point about Infinispan potentially moving to Caching makes sense, considering that it is available as an embedded Java library (even if it kind of defeats the point of it being distributed) and the fact that it [implements the JCache standard](http://infinispan.org/tutorials/simple/jcache/).

**Comment by jbduncan** [comment]
On the topic of HBase, I can't tell if it deserves to stay, as I don't know how often Java developers use it outside the Hadoop ecosystem.

And talking about Hadoop, I think that Hadoop itself _should_ stay (it's currently in the Ancients section), because IIRC one can write Hadoop MapReduce jobs in Java, even if it's not the most popular language for doing so AFAIK.

**Comment by jbduncan** [comment]
LGTM @Moshe-Immerman!

Before I merge this, would you mind squashing the two commits together, so that when I do merge it, the Git history looks a bit cleaner. :)

**Comment by Moshe-Immerman** [comment]
@jbduncan  done

**Comment by jbduncan** [comment]
@Moshe-Immerman Thanks!

@akullpp, does this look okay to merge to you?

**Comment by akullpp** [comment]
OpenTSDB has a Java API I think.

Overall it looks good.

**Pull request merged**
