### PR TITLE
Add pojo-tester library

### PR DESCRIPTION
**Pull request by sta-szek**
pojo-tester is java testing library which automatically (just pass a class name) performs pojo methods tests.
More information can be found on project's site: http://www.pojo.pl/

### CODE REVIEW

**Comment by sta-szek** [comment]
@akullpp is something wrong with this PR?

**Comment by akullpp** [comment]
So you are the author of said library, can you elaborate how it's different from https://github.com/oshoukry/openpojo and why did you write it since testing getter/setter and so on is a controversial issue.

**Comment by sta-szek** [comment]
Differences are described with details here: http://www.pojo.pl/comparison/

**Comment by sta-szek** [comment]
thanks ;)

**Pull request merged**
