### PR TITLE
Add Classgraph

### PR DESCRIPTION
**Pull request by ununhexium**
Hello,

I think it deserves more visibility.

I didn't find any introspection lib on this page.

I've been using other libraries for introspection, mostly Reflections
and would have loved seeing that one in this list.

Stackoverflow don't mention it much unfortunately when looking for a
reflection framework.

https://www.baeldung.com/classgraph

It has better documention than the alternatives, been working perfectly
for me so far. They have a no bug policy.

Has MIT license.

It's beeing honest about all the alternatives and lists them.

Still maintained.

### CODE REVIEW

**Comment by shathor** [comment]
There are quite a few popular libraries in this area, e.g.:
* https://github.com/ronmamo/reflections
* https://github.com/EsotericSoftware/reflectasm
* https://github.com/jOOQ/jOOR
* http://projetos.vidageek.net/mirror/mirror/

**Comment by ununhexium** [comment]
So should I add them all or none of them?

**Comment by shathor** [comment]
If you ask me, it would be nice if you'd add them all. Maybe in a subcategory "Reflection" or "Introspection".

**Comment by ununhexium** [comment]
Updated PR with all the mentioned libs and their official description 1 liner.

**Pull request merged**
