### PR TITLE
Resolve #697: Add licenses

### LINKED ISSUE #697: Add licenses
Would be nice to see the licenses which are used for the latest versions of the entries.

Especially for commercial use in enterprise settings this is very important.

This is quite complicated since there can be multiple applicable licenses.

### PR DESCRIPTION
**Pull request by heldev**
I wrote a small script that adds repo and license info to every line.
Now we need to decide how the final result should look like so I can amend the script and finally do some manual edits and checks.
I looked at the list of [GitHub icons](https://gist.github.com/rxaviers/7360908) but didn't find anything matching really well, we can have something like:

- [Cobertura](https://cobertura.github.io/cobertura) - Relies on offline (or static) bytecode instrumentation and class loading to collect code coverage metrics. (gpl-2.0)

for the following list of licenses:
-  agpl-3.0
-  gpl-2.0
-  gpl-3.0

Let me know if any other format works better.

PS btw we do not need licenses for things like cobertura, because it's a tool, right ?

### CODE REVIEW

**Comment by akullpp** [comment]
I think they should use the [SPDX identifiers](https://spdx.org/licenses/). Format seems good. We could also only display difficult licenses like *GPL to reduce visual clutter. Can you share the script?

**Comment by heldev** [comment]
My notes on what was checked manually:

mapstruct -> apache 2
ASM -> 3-Clause BSD License
byteman -> LGPL 2.1 
javassist -> MPL
jline3 -> BSD-3-Clause
text-io -> apache 2
checkstyle -> lgpl 2.1
jqassistant -> GPLv3
pmd -> BSD-style, apache-2 and part of pmd-scala is lgpl-3
sonar-java -> lgpl-3
INRIA/spoon -> mit or CeCILL-C
jacoco -> Eclipse Public License
adt4j -> BSD 3-clause
antlr4 -> BSD license
javacc -> custom BSD-like Sun Microsystems
jflex -> 3-clause BSD-style license
dotenv -> mit
ini4j -> Apache 2
choco-solver -> BSD 4-Clause License 
jackson-csv -> apache 2
uniVocity/univocity-parsers -> apache 2
flyway -> apache 2
h2 -> MPL 2.0 or EPL 1.0
jdbi -> apache 2
jinq -> BSD 2-clause
jooq -> apache 2 or commercial
liquibase -> apache 2
mapdb -> apache
realm-java -> apache 2
speedment -> Apache 2
hyperminihash-java -> apache 2
protobuf -> BSD 3-clause
feather -> apache 2
hk2 -> new rep Eclipse Public License - v 2.0 
jaywire -> GNU Lesser General Public License v3
dcevm -> No license
javaparser -> lgpl or apache
manifold -> apache 2
noexception -> apache 2
atomix -> apache 2
axonframework -> apache 2
jgroups -> Apache License 2.0
orbit ->  BSD 3-Clause License
quasar -> Eclipse Public License v1.0 or GNU Lesser General Public License version 3.0
atomikos -> apache 2 or proprietary 
narayana -> LGPL 2.1 License
izpack -> apache 2
jitpack -> proprietary
really-executable-jars-maven-plugin -> apache 2
docx4j -> apache 2
janala2 -> mit
checker-framework -> GNU General Public License, version 2 (GPL2), with the classpath exception + mit for some parts
daikon -> unrestricted
jpf - apache 2
JmlOk2 -> GPL v3
key-project -> GNU General Public License
openjml -> GPLv2
derive4j -> core annotation processor GNU GPL v3, Other useful modules (annotation and processor-api)  GNU LGPL v3, Build scripts and examples BSD-3
fugue -> apache 2
functionaljava -> BSD 3 license
vavr -> apache 2
jmonkeyengine -> New BSD (3-clause) License
libgdx -> Apache 2 License
lwjgl -> BSD license
geotoolkit -> LGPL 2.1
Spatial4j -> eclipse
scene-builder -> bsd
koloboke -> Apache 2.0
async-http-client -> apache 2
netbeans -> dual license consisting of the Common Development and Distribution License (CDDL) v1.0 and the GNU General Public License (GPL) v2
visual code -> mit
thumbnailator -> no restrictions license
dsl-json -> custom bsd like
genson -> apache 2
jackson -> apache 2
json-iterator -> mit
fastjson -> apache 2
openjdk -> GPLv2 with linking exception
avian -> ISC License
graal -> per component, most components GPL 2 with Classpath exception
corretto -> GPLv2 with CPE
liberica -> GPL v 2 with CPE
openj9 -> Apache License 2.0 or Eclipse Public License 2.0 with a secondary compatibility license for the OpenJDK project's GPLv2 license
openjdk -> GPL v 2 with CPE
redhat open jdk -> GPL 2 with cpe
zulu -> gpl 2 with cpe
graylog -> gpl 3
kibana -> some parts elastic license
logback -> Eclipse Public License 1 or LGPL 2.1
logstash -> some parts elastic license
slf4j -> mit
h20 -> apache 2
weka -> gpl
hermes -> apache 2
rabbitmq-java-client -> mpl 1.1 or apache 2 or gpl2
ff4j -> apache 2
FizzBuzzEnterpriseEdition -> no explicit license
javacv -> apache 2 or GPL2 with cpe
JavaX -> no explicit license
jpad -> no explicit license
lightadmin -> apache 2
service-proxy -> apache 2
multi-os-engine -> apache 2
maven-polyglot -> EPL 1
smooks -> LGPL license, Version 3.0.
micronaut -> apache 2
inspectit -> apache 2
jaegertracing/jaeger-client-java -> apache 2
kamon -> apache 2
metrics -> apache 2
prometheus -> apache 2
javacpp -> apache 2 or GPL 2+ with cpe
jna -> LGPL, version 2.1 or later or Apache Software License, version 2.0
jnr-ffi -> apache 2 or lgpl 3+
cogcomp-nlp -> Research and Academic Use License
CoreNLP -> GPL 3
LingPipe -> proprietary 
sshj -> apache 2
ebean -> apache 2
hibernate -> lgpl 2.1
mybatis -> apache 2
flyingsaucer -> lgpl 2.1
openhtmltopdf -> LGPL 2.1 (An exception to this is the pdf-a testing module, which is licensed under the GPL)
honest-profiler -> mit
jHiccup -> bsd 2
jitwatch -> bsd
jmh -> gpl 2
LatencyUtils -> bsd or cc0
zt-process-killer -> apache 2
akka -> apache 2
reactive-streams-jvm -> cc0
dropwizard -> apache 2
elide -> apache 2
rest.li -> apache 2
Resteasy -> apache 2
restlet-framework-java -> Apache Software License 2.0 or the Eclipse Public License 1.0
swagger -> apache 2
dmelt -> lgpl
gs-core -> CeCILL-C or lgpl
JGraphT -> LGPL) 2.1 or epl 2
jgraphx -> bsd
elastic -> apache 2 and x-pack as elastic license
Bouncy Castle -> MIT X 
hdiv -> apache 2
keycloak -> apache 2
picketlink -> apache 2
ws liberty -> proprietary 
handlebars.java -> apache 2
jtwig -> apache 2
pebbletemplates -> BSD 3-Clause
rocker -> apache 2
thymeleaf -> apache 2
hoverfly-java -> apache 2
jbehave -> BSD-style
thucydides -> apache 2
java-faker -> apache 2
arquillian -> apache 2
junit -> epl
assertj -> apache 2
jmockit -> mit
crash -> LGPL, version 2.1
embulk -> apache 2
gephi -> CDDL 1.0 and GNU General Public License v3
jade -> LGPL 2
protege -> bsd
jabba -> apache 2
play -> apache 2
ratpack -> apache 2
vaadin flow -> apache 2

**Comment by heldev** [comment]
Two notes:
1. There are 2 entries with "no explicit license" tags. Because https://help.github.com/en/articles/licensing-a-repository#choosing-the-right-license basically says that nobody can really do anything with project with no license. Let me know if these tags are not needed

2. The [mapsforge](https://github.com/mapsforge/mapsforge) project has a custom license based on LGPL, which allows you to freely link it with your app. Let me know if we want to add a tag to the project

**Comment by heldev** [comment]
@akullpp here is the script. I've added some instructions, but let me know if there any troubles
https://gist.github.com/heldev/24d4449b935248cca6a226fcf380e548

**Comment by heldev** [comment]
PS sorry forgot to mention that it's ready to merge

**Pull request merged**
