### PR TITLE
 Move failsafe lib to distributed apps

### PR DESCRIPTION
**Pull request by MALPI**
I consider failsafe to be in distributed applications sections since the provided patterns are used in this environment.

### CODE REVIEW

**Comment by jbduncan** [comment]
I think this change is reasonable.

By this logic, javaslang-circuitbreaker (which was recently renamed to resilience4j and relocated to https://github.com/resilience4j/resilience4j) should be moved as well. So @MAPLI, would you mind moving, renaming, and changing the link for javaslang-circuitbreaker as well? :)

**Comment by jbduncan** [comment]
Sorry, meant to /cc @MAPLI. :P

**Comment by jbduncan** [comment]
(Never mind, seems that GitHub automatically normalises usernames in uppercase to lowercase when writing messages, on mobile at least.)

**Comment by MALPI** [comment]
Done @jbduncan

**Comment by jbduncan** [comment]
@MAPLI Thanks!

@akullp, do you have any thoughts on this PR before I go and merge it?

**Comment by MALPI** [comment]
@jbduncan you actually do a typo. it's MALPI and not mapli. See the "L" ;)

**Comment by jbduncan** [comment]
Oops, silly me! Thanks for the correction, @MALPI. ;)

**Comment by akullpp** [comment]
@jbduncan Go ahead and merge it, no need to ask.

My only thought about this is that the distributed applications category is too vague.

**Comment by jbduncan** [comment]
Thanks @akullpp for the clarification.

I'm not too concerned about the distributed applications category, but I do wonder if it could be split into two or more sections. Maybe an individual section for the failure-handling libraries (Hystrix, Failsafe, resilience4j...)?

**Pull request merged**
