### PR TITLE
Added MinimalFTP

### PR DESCRIPTION
**Pull request by Guichaguri**
MinimalFTP is a lightweight, simple FTP server written in Java. It is licensed under GPL 3.0, but I'll probably be re-licensing it under Apache 2.0
It supports 58 FTP commands, TLS/SSL, custom file system, custom user authentication, custom commands, etc.

### CODE REVIEW

**Comment by jbduncan** [comment]
Hi @Guichaguri, thanks for submitting this PR.

I'm hesitant to add MinimalFTP for two reasons:
1. It doesn't really match the category description of *Servers which are specifically used to deploy applications.*
2. It's only been open-sourced for 18 days at the time of me writing this, so it's had very little time to prove its awesome-ness to the wider Java community.

Unless @akullpp has any further thoughts, I'd vote to close this PR.

**Comment by Guichaguri** [comment]
1. Which one would be the right category?
2. I understand. I didn't know that it needs more than a half a month of existence, you should probably specify that in the guidelines. Until then, I'll be closing this PR.

Thanks :)

**Comment by jbduncan** [comment]
@Guichaguri 
1. I think the right category would be **Miscellaneous**, as there's no other entry in awesome-java yet for an FTP server, IIRC. Once awesome-java has two or more FTP server entries, then they would deserve to be moved into their own category, e.g. **FTP Servers**.
2. Yes, sorry, this conversation has made me realise that we're missing two important pieces of information in the contribution guidelines: firstly that new entries likely will not be added if they've not been around "long enough" to prove their awesomeness, e.g. 3 months or so; and secondly that entries which don't fit any of the pre-existing specialised sections should go under **Miscellaneous**. I'll open an issue to have these addressed in the future. :)

**Comment by GuSilva230** [comment]
There is also a [FTP server from Apache](https://mina.apache.org/ftpserver-project/), it's not actively maintained but it's stable.

**Comment by jbduncan** [comment]
@GuSilva230 If you think that Apache FTPserver would be good to include in awesome-java, I'd suggest that you open a new issue or PR for it, as otherwise we're likely to forget to come back to it. :)

**Comment by Guichaguri** [comment]
@jbduncan I've created a new PR for MinimalFTP #644

**Pull request closed without merging**
