### PR TITLE
Add Apache Commons CLI

### PR DESCRIPTION
**Pull request by Soheibooo**

### CODE REVIEW

**Comment by Soheibooo** [comment]
Adding KryoNet too. Maybe I should emphasize its simplicity.

**Comment by jbduncan** [comment]
Hi @Soheibooo. As I was glancing over my new GitHub messages, I just happened to notice you added KryoNet to this PR. Would you kindly revert it here and open it in a new PR please, as AFAICT it's not related to Apache Commons CLI.

**Comment by jbduncan** [comment]
> Adding KryoNet too. Maybe I should emphasize its simplicity.

Argh, kinda ninja'd!

But I think my last comment still stands. :)

**Comment by Soheibooo** [comment]
Right! Correcting right away.

**Comment by jbduncan** [comment]
Ta. :+1:

**Comment by akullpp** [comment]
We don't add every Apache Commons subproject same as Spring or other multi-project frameworks. Sorry.

**Pull request closed without merging**
