### PR TITLE
Added Financial

### PR DESCRIPTION
**Pull request by bobbilee19**
Payment category added.

Square Java SDK added as initial suggestion in this category. https://github.com/square/connect-java-sdk/ (via: https://developer.squareup.com/docs/sdks)

### CODE REVIEW

**Comment by shathor** [comment]
Wouldn't it be better to add a more generic category, such as "Finance"?

**Comment by bobbilee19** [comment]
@shathor yeah for sure good idea!

**Comment by bobbilee19** [comment]
@shathor added your suggestion

**Comment by akullpp** [comment]
Hey, the contribution guidelines should state that it's a bad idea to create a category for one element only. Could you add two more or move it to the Misc section?

**Comment by bobbilee19** [comment]
Hey sorry for delay here! Do these work? https://github.com/stripe/stripe-java and https://github.com/paypal/PayPal-Java-SDK - If so I can add them in today!

**Comment by akullpp** [comment]
Yes would work out. Though they all are SDKs, other interesting stuff are:

https://github.com/paritytrading/parity
https://github.com/paritytrading/philadelphia

**Comment by bobbilee19** [comment]
@akullpp Sorry for delay, I added Parity and Philadelphia, did you still want me to add paypal and stripe? Or good to go? Thanks!

**Comment by akullpp** [comment]
Perfect thanks!

**Pull request merged**
