### PR TITLE
Adding fastThread tool

### PR DESCRIPTION
**Pull request by brunocvcunha**
Free tool built by the same provider of gceasy.io, fastthread.io allows you to explore and identify problems using thread dumps.

### CODE REVIEW

**Comment by brunocvcunha** [comment]
Hi @akullpp 

Any reason why tagged it with ![c]?
AFAIK fastThread is completely free.

Thank you!

**Comment by akullpp** [comment]
It's closed source and has public cloud hosted interface. Self-hosting costs money: http://fastthread.io/how-to-analyze-thread-dumps-faq.jsp

For me this sounds like a business plan.

**Comment by brunocvcunha** [comment]
Sounds good, thanks for the heads up @akullpp.
I have been using for months and even automated using the APIs, and wasn't aware that they provide the hosted solution.

BTW, it's still not very clear to me what the `$` means. Following the same idea, should tools like Bamboo, Bintray, Nexus, IntelliJ IDEA also carry the sign? Or maybe we could clarify on the README.

**Comment by akullpp** [comment]
Yup, you are right. There are other mainly commercial entries which do not contain the symbol since I introduced it a few months ago but didn't change the old stuff. Everyone is welcome to make the changes.

**Pull request merged**
